### ISSUE TITLE
7.2 离散化区间

### ISSUE THREAD

**Issue by GengShen** [BrambleXu/pydata-notebook#14]
> 原文写为"18 ~ 25, 26 ~ 35, 36 ~ 60, >60",应为"19 ~ 25, 26 ~ 35, 36 ~ 60, >60"

**Comment by BrambleXu** [comment]
我确认了下，英文原版里确实是18，你能再确认一遍吗？下面是英文原版里相关的部分截图

![2017-12-30 9 28 01](https://user-images.githubusercontent.com/10768193/34454538-5db62fba-eda8-11e7-9776-3f0b3aa15d33.png)

**Comment by GengShen** [comment]
那英文版也写错了.
请参照out[78], 如果(25,35] 对应26 to 35的话, 那么(18, 25]就应该对应 19 to 25才对.

**Comment by BrambleXu** [comment]
有道理，你很真细心啊，谢谢，我会更改的

**Comment by GengShen** [comment]
没事, 我在拜读你的翻译. 不介意提出更多的问题吧?

**Comment by BrambleXu** [comment]
不介意的，尽管提

2017年12月30日 +0800 21:45 GengShen <notifications@github.com>，写道：

**Comment by GengShen** [comment]
好的
