### ISSUE TITLE
第八章 join翻译

### ISSUE THREAD

**Issue by GengShen** [BrambleXu/pydata-notebook#16]
第八章 join应该对应关系数据库中的join, 所以应该翻译成"连接"

**Comment by BrambleXu** [comment]
能指出具体的地方吗，我找起来会方便些

2017年12月30日 +0800 21:52 GengShen <notifications@github.com>，写道：

**Comment by GengShen** [comment]
比如8.1 的大标题:
CHAPTER 8 Data Wrangling: Join, Combine, and Reshape（数据加工：加入, 结合, 变型）
其中join对应于sql语句中的join, 作用是连接.
combine我还没看到

**Comment by BrambleXu** [comment]
combine是不是翻译成合并会好一些，还是说结合也可以？

**Comment by BrambleXu** [comment]
join的话我会把第八章全部三节的翻译都更新一下的

**Comment by GengShen** [comment]
好的
