### ISSUE TITLE
善意的提醒

### ISSUE THREAD

**Issue by TESTAUDICA** [BrambleXu/pydata-notebook#21]
同学，你的开源精神是好的。但我要善意的提醒你版权问题。翻译权并不在原作者手中，而是由国内出版社买断的。你没有取得出版社翻译合同的话，擅自翻译，可能会引起版权纠纷。

**Comment by BrambleXu** [comment]
谢谢提醒，那么在这种情况下我需要做些什么呢？

2018年2月4日 +0900 12:24 Xu Jing Yi <notifications@github.com>，写道：

**Comment by BrambleXu** [comment]
我正在联系国内的出版社，如果对方觉得有问题的话，虽然觉得有点可惜，但我会主动删除这个项目的。再次感谢您的提醒。

2018年2月4日 +0900 12:24 Xu Jing Yi <notifications@github.com>，写道：
