### ISSUE TITLE
Renaming files to make git clone work on Windows

### ISSUE THREAD

**Issue by nmweizi** [BrambleXu/pydata-notebook#22]
见 https://github.com/jvns/pandas-cookbook/pull/25

windows下，git clone 文件名里不能有问号。

error: unable to create file Chapter-01/1.1 What Is This Book About?（这本书是关于什么的）.ipynb: Invalid arg
ument
error: unable to create file Chapter-01/1.2 Why Python for Data Analysis?（为什么使用Python做数据分析）.ipynb
: Invalid argument
Your branch is up-to-date with 'origin/master'.

**Comment by BrambleXu** [comment]
我更新了文件名，去掉了问号，你可以再试一下

**Comment by nmweizi** [comment]
搞定，thx
