### ISSUE TITLE
大概什么时候出版呀

### ISSUE THREAD

**Issue by zhaochuanyun** [BrambleXu/pydata-notebook#23]
rt

**Comment by BrambleXu** [comment]
这个我也说不准，国内的译者已经翻译完了，剩下的主要就是出版社那边的工作了，应该不会太久

2018年3月20日 +0900 15:45 MrCoCo <notifications@github.com>，写道：

**Comment by ahlixinjie** [comment]
很期待, 也很需要, 如果能发email问一下大概出版时间就好了

**Comment by BrambleXu** [comment]
问过了，大概五月多

2018年3月27日 +0900 23:15 ahlixinjie <notifications@github.com>，写道：

**Comment by ahlixinjie** [comment]
thx a lot

**Comment by LJXLJXLJX** [comment]
已经五月了。。。

**Comment by pynashgo** [comment]
是哪个出版社的能告诉我么？

**Comment by BrambleXu** [comment]
华章出版社

**Comment by Ctipsy** [comment]
好遗憾，刚买了本中文第一版。
不会马上第二版就面世了吧😭

**Comment by BrambleXu** [comment]
又问了一下，好像又到了7月

**Comment by Ctipsy** [comment]
应该是机械工业出版社，华章图书；

**Comment by LJXLJXLJX** [comment]
@BrambleXu 心好累 虽然英文版的也看得懂 但还是中文版的看着省心啊。。。

**Comment by BrambleXu** [comment]
commit-94ab376，我只能帮到这里了

**Comment by jiahe224** [comment]
94ab376是最终完整版吗？ @BrambleXu

**Comment by BrambleXu** [comment]
@jiahe224 是的

**Comment by LJXLJXLJX** [comment]
已经七月了 貌似还没出。。。

**Comment by Ctipsy** [comment]
哈，又收到了github邮件通知。
这本书，其实应该当成手册来看，我之前过了一遍但是看完一段时间后，基本忘差不多了
后来基本上是在实际敲代码中，需要哪块知识，就是查资料，或者翻书。

**Comment by LJXLJXLJX** [comment]
@Ctipsy 个人比较喜欢纸质书 所以很期待

**Comment by Ctipsy** [comment]
@LJXLJXLJX   嗯嗯，纸质书翻起来快，有笔记的话更是温故知新
