### ISSUE TITLE
thx for your prompt in readme

### ISSUE THREAD

**Issue by Ctipsy** [BrambleXu/pydata-notebook#24]
thx for your hard&Selfless work😄

**Comment by BrambleXu** [comment]
I am glad you found the right way :)

**Comment by Ctipsy** [comment]
in section 2.3 , under code cell In [70]
 I think 类型转换 will be better instead of 类型塑造（Type casting）.

**Comment by BrambleXu** [comment]
Yes, you are right. But because I already delete this part in master branch, so I can not change the contents. I am sorry for that.
