### ISSUE TITLE
页面报503了，不能访问啊

### ISSUE THREAD

**Issue by cocowool** [BrambleXu/pydata-notebook#4]
页面报503了，不能访问啊

**Comment by BrambleXu** [comment]
这个是因为jupyter nbviewer服务器那边宕机了，以前也出现过这样的情况，过段时间应该能修复。建议把整个笔记文件下载到本地，用jupyter打开查看

**Comment by BrambleXu** [comment]
已经能正常访问了

**Comment by cocowool** [comment]
看到了，感谢，赞～！
